# Generated by Django 4.2.5 on 2024-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sectors', models.CharField(max_length=100)),
                ('holding', models.FloatField()),
                ('fname', models.CharField(max_length=100)),
                ('ftype', models.CharField(max_length=50)),
            ],
        ),
    ]
