version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/stock-app-database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cr3tP@55W04d2024
      - POSTGRES_USER=stock_user
      - POSTGRES_DB=stocks